#!/usr/bin/env node

var http = require('http');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});

  switch(req.url) {
    case "/slow":
      setTimeout(function() {
        res.end('Hello Tortoise\n');
      }, 1000);
      break;
    case "/fast":
      res.end('Hello Cheetah\n');
      break;
  }
}).listen(1337, '127.0.0.1');

console.log('Server running at http://127.0.0.1:1337/');
